# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FXVersionCheckDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FXVersionCheckDemo

  pod 'ObjectMapper', '~> 3.1'

  target 'FXVersionCheckDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FXVersionCheckDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
