# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FXShareSDKDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FXShareSDKDemo
  # 主模块(必须)
  pod 'mob_sharesdk'
   
  # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
  pod 'mob_sharesdk/ShareSDKUI'
   
  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
  # pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
  
  # ShareSDKPlatforms模块其他平台，按需添加
  # 如果需要的平台没有对应的平台语句，有2种情况——1、不需要添加这个平台的语句，如Twitter就是这个情况。2、ShareSDK暂时不支持此平台。
  # pod 'mob_sharesdk/ShareSDKPlatforms/RenRen'
  # pod 'mob_sharesdk/ShareSDKPlatforms/AliPaySocial'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Kakao'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Yixin'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Copy'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Evernote'
  # pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Instagram'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Instapaper'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Line'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Mail'
  # pod 'mob_sharesdk/ShareSDKPlatforms/SMS'
  # pod 'mob_sharesdk/ShareSDKPlatforms/WhatsApp'
  # pod 'mob_sharesdk/ShareSDKPlatforms/MeiPai'
  # pod 'mob_sharesdk/ShareSDKPlatforms/DingTalk'
  # pod 'mob_sharesdk/ShareSDKPlatforms/YouTube'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
  # pod 'mob_sharesdk/ShareSDKPlatforms/Dropbox'
   
  # 使用配置文件分享模块（非必需）
  # pod 'mob_sharesdk/ShareSDKConfigurationFile'
   
  # 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
  pod 'mob_sharesdk/ShareSDKExtension'
  
  target 'FXShareSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FXShareSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
